[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[profile.dev]
overflow-checks = false

[dependencies]
rand = "0.8.5"
phf = { version = "0.11", features = ["macros"] }
u4 = "0.1.2"
bytemuck = "1"
minifb = "0.27.0"

[build]
target = ["x86_64-unknown-linux-gnu", "wasm32-wasip1"]
