[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[profile.dev]
overflow-checks = false

[dependencies]
rand = "0.8.5"
phf = { version = "0.11", features = ["macros"] }
u4 = "0.1.2"
bytemuck = "1"
ogl33 = { version = "0.3.0" }
beryllium = "0.13.3"
imagine = "0.5.1"
ultraviolet= "0.9.2"
